name: x-hec-solution
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.10
  - pip=22.3.1
  - matplotlib=3.8.0
  - pip:
    - pip-tools==7.3.0
    - pandas==2.1.1
    - mlflow==2.7.1
    - scikit-learn==1.3.1
    - numpy==1.26.1


